name: 'Deploy to Cloud Run from Source (WIF)'

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: "terraform-479314"
  REGION: "europe-north1"
  SERVICE_NAME: "my-static-website-gcp-123"
  GCP_SA_EMAIL: "github-deployer@terraform-479314.iam.gserviceaccount.com"
  
  WIF_PROVIDER: "projects/420265886954/locations/global/workloadIdentityPools/github-pool/providers/github-provider" 

# 3. Define the deployment job
jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    
    permissions:
      contents: 'read'
      id-token: 'write' 

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

    
      - id: 'auth'
        name: 'Authenticate to Google Cloud (via WIF)'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ env.WIF_PROVIDER }}
          service_account: ${{ env.GCP_SA_EMAIL }}

  
      - name: 'Deploy to Cloud Run'
        id: 'deploy' 
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          source: './'

  
      - name: 'Show output'
        run: |
          echo "Cloud Run Service URL: ${{ steps.deploy.outputs.url }}"
