name: 'Deploy to Cloud Run from Source (Service Account Key)'

on:
  push:
    branches:
      - main
  workflow_dispatch:


env:
  PROJECT_ID: "terraform-479314"
  REGION: "europe-north1"
  SERVICE_NAME: "my-static-website-gcp-123"
 
  GCP_SA_EMAIL: "github-deployer@terraform-479314.iam.gserviceaccount.com"
  

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    
    permissions:
      contents: 'read'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      
      - id: 'auth'
        name: 'Authenticate to Google Cloud (via Service Account Key)'
        uses: 'google-github-actions/auth@v2'
        with:
        
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          
          
          workload_identity_provider: ''
          token_format: '' 

      
      - name: 'Deploy to Cloud Run'
        id: 'deploy' 
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          source: './'
          
          flags: '--allow-unauthenticated'

      
      - name: 'Show output'
        run: |
          echo "Cloud Run Service URL: ${{ steps.deploy.outputs.url }}"
